### ISSUE TITLE
Is Unity 2018.3 supported by v5.8.5?

### ISSUE THREAD

**Issue by teh1archon** [Pushwoosh/pushwoosh-unity#46]
Hello,

I've upgraded the project from 2017.4 to 2018.3.7f1. and now PW doesn't work. 
I've tried to download the latest version of PW unitypackage file and overwrite in my project but it just ended up in the whole project not compiling (if I remember correctly it was due to android dependencies + api changes).
What can I do?

**Comment by wfhm** [comment]
Hi @teh1archon,

I've just tried sending pushes to the app built with 2018.3.2f1, and it worked just fine. I did not have a chance to check it with the latest version, however it seems like there were no major changes, so it should also be working.

Could you please provide a bit more details on the build issues with the latest plugin versions?

**Comment by teh1archon** [comment]
Hello and thanks for the reply. For some reason, my edit to my original post didn't pass.

Anyways we're working with 2018.3.6 (and then moved to 2018.3.7) but the fault was actually with us and the fix was to explicitly set the scripts execution order via Player Setting -> Script Order Execution. For some reason, Unity 2017 ran all the scripts in order that made sense and 2018 had race conditions.

I did have compilation error importing the latest version of PushWoosh via the unitypackage and overwriting but due to time constraints, I had to immediately roll back so I don't have the console errors. Those as well might have been solely on us.

Thank you for replying quickly anyhow :)
